#define DRAW_MODE_2D_MIX -3
#define DRAW_MODE_2D -2
#define DRAW_MODE_WHITE -1
#define DRAW_MODE_DEFAULT 0
#define DRAW_MODE_CYLINDER 2
#define DRAW_MODE_EDGES 3
#define DRAW_MODE_SKY 4
#define DRAW_MODE_BILLBOARD 5